### ISSUE TITLE
Does Stefan own the Julia logo/trademark?

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia-logo-graphics#14]
@StefanKarpinski per:

> They are "tidied up" versions of the original logo by Stefan Karpinski, with whom remains all the copyrights and trademarks.

Do you still own this or was it transferred to JuliaComputing?

**Comment by cormullion** [comment]
According to `git blame`, I wrote that a few years before Stefan posted this in 2017:

https://discourse.julialang.org/t/trademark-guidelines-fair-use-policy-for-julia-name-logo/3404/4?u=cormullion

So the text in the README definitely needs to improved and updated with that status, if nothing else!

**Comment by StefanKarpinski** [comment]
I still own it. At some point when there's a proper Julia foundation, I can transfer the copyright to that.
