### ISSUE TITLE
SVG paths in the logos are not closed

### ISSUE THREAD

**Issue by kimikage** [JuliaLang/julia-logo-graphics#17]
There are two different types of problems.

## 1. non-dot glyphs
The first problem concerns the non-dot glyphs in the logos.

https://github.com/JuliaLang/julia-logo-graphics/blob/f3a09eb033b653970c5b8412e7755e3c7d78db9e/images/julia-logo-color.svg#L4

```
# "j" of julia
M 67.871094 164.3125
C 67.871094 171.847656 67.023438 177.933594 65.328125 182.566406 
...snip...
L 67.871094 76.929688 
L 67.871094 164.3125 # this should be `Z`
# "u" of julia
M 104.738281 79.414062 
L 104.738281 139.214844 
```
They have the same coordinates as the "M" points but are not topologically closed (without "Z").
The output paths are closed with the current version of Luxor. 🤔 

## 2. dots
The second problem concerns the dots in the logos.
The paths of dots are not closed either.
However, for this matter, the path definitions in Luxor are not closed.

https://github.com/JuliaGraphics/Luxor.jl/blame/71415993d515e2ef4b2ae461d1b59793bd5facb0/src/juliagraphics.jl#L191-L221

Note that the arc (”A”) of the SVG path is a bit complicated, so I agree with the approximation with four Bezier curves.

## off-topic
![julialogo](https://github.com/JuliaLang/julia-logo-graphics/assets/12679384/54b71633-743f-4689-8798-6fee6f382be3)

The marked line segment is formally defined as a curve.
https://github.com/JuliaGraphics/Luxor.jl/blame/71415993d515e2ef4b2ae461d1b59793bd5facb0/src/juliagraphics.jl#L109
They have the same x-coordinate, i.e., they are on a straight line. 😄

**Comment by kimikage** [comment]
The following SVGs are relevant. The PDFs have not been checked.
```
images/julia-logo-color.svg
images/julia-logo-dark-nocolor.svg
images/julia-logo-dark.svg
```

There is a similar problem in `images/julia-dots.svg`.
However, the dots are drawn with `circle`, which may be a backend issue.
https://github.com/JuliaGraphics/Luxor.jl/blame/71415993d515e2ef4b2ae461d1b59793bd5facb0/src/juliagraphics.jl#L300

**Comment by cormullion** [comment]
@kimikage Thanks! 

The files here weren't created with Julia or Luxor (which they likely predate). I think they were created in some editor and then minimized using [svgomg](http://svgomg.net) or similar to reduce file size to a minimum. 

I don' think there's an official design specification anywhere. (And certainly nothing as detailed as [this branding guide](https://www.goldennumber.net/wp-content/uploads/pepsi-arnell-021109.pdf).) As these graphics are intellectual property (ie copyright/trademark of Stefan and the Julia project), I think it's OK to use derivative versions to make Julia-related graphics in Luxor, but I wouldn't want to get into modifying or prescribing anything here.

**Comment by kimikage** [comment]
I understand.

I noticed this problem in the process of generating a mesh from the SVG.
https://discourse.julialang.org/t/how-to-construct-a-mesh-from-faces-containing-triangleface-and-quadface-with-geometrybasics/112001/6

I'm leaving this issue open in case anyone else encounters a similar problem.
Of course, this can be closed.

**Comment by StefanKarpinski** [comment]
@cormullion If you have Luxor code to generate correct SVGs that look right, I'd be happy to switch to having the output of those be official rather than these, which were created by @jiahao many years ago from a PDF exported from Keynote. (We are design professionals here!) Having Luxor code that generates the SVGs and having those be official is much cleaner and preferable!
