### ISSUE TITLE
julia-logo-color.svg has a white background

### ISSUE THREAD

**Issue by rayegun** [JuliaLang/julia-logo-graphics#20]
Hi!

Is it intentional that there's a white background on the svg for the main logo? I would expect no background.

**Comment by cormullion** [comment]
That’s so that you can see it in Dark Mode (eg the github home page).

**Comment by cormullion** [comment]
Perhaps it should be replaced with this one...

[julia-logo-color-no-background.svg.zip](https://github.com/user-attachments/files/16126437/julia-logo-color-no-background.svg.zip)

**Comment by StefanKarpinski** [comment]
I can't see that in my phone but if it's a transparent background version then 👍

**Comment by cormullion** [comment]
I think I inadvertently merged this directly. Sorry... 😊
