### ISSUE TITLE
Make this an official JuliaLang repo

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia-logo-graphics#4]
It would be nice to have this repo to be an official JuliaLang repo.

**Comment by StefanKarpinski** [comment]
@cormullion, if you make me an owner of this repo, I can transfer it to @JuliaLang, which seems like a more fitting place for such a core piece of the Julia identity. I'll make you an owner there as well.

**Comment by cormullion** [comment]
Is that a transfer ownership thing on github? You're probably already a member of JuliaGraphics...

**Comment by StefanKarpinski** [comment]
I am not as far as I can tell. You would need to add me as an owner to the JuliaGraphics org.

**Comment by cormullion** [comment]
An invitation should work...? It’s about time, you’re very welcome :)

**Comment by StefanKarpinski** [comment]
I’m now a member but not an admin or an owner and do not have sufficient permissions to transfer the repo (or do anything administrative).

**Comment by StefanKarpinski** [comment]
Done!

**Comment by ViralBShah** [comment]
Thanks both for the quick work here!
